version: '3.7'

services:
  backend:
      build: .
      command: bash -c "
                python ./manage.py migrate --fake-initial && 
                python ./manage.py runserver 0.0.0.0:8000
              " 
      volumes:
        - ./ryde:/code
        - .env:/code/.env
      ports:
        - 8000:8000
        - 8001:8001
      links:
        - db

  db:
      image: mongo:latest
      ports:
        - 27017:27017
      restart: unless-stopped 
      environment:
        MONGO_INITDB_ROOT_USERNAME: "${DATABASE_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      volumes:
        - ./db:/data/db
