# Generated by Django 2.2.16 on 2021-11-01 17:01

from django.db import migrations
import djongo.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=djongo.models.fields.EmbeddedModelField(model_container=users.models.Address, null=True),
        ),
    ]
